CREATE TABLE role (
                      id UUID PRIMARY KEY,
                      role_type VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE user_table (
                            user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            email VARCHAR(255) NOT NULL UNIQUE,
                            username VARCHAR(255) NOT NULL UNIQUE,
                            name VARCHAR(255) NOT NULL,
                            gender VARCHAR(20) NOT NULL,
                            phone_number VARCHAR(20) NOT NULL UNIQUE,
                            password VARCHAR(255) NOT NULL,
                            image VARCHAR(255),
                            is_enable BOOLEAN NOT NULL,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                            provider VARCHAR(20) NOT NULL
);

CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id UUID NOT NULL,

                            PRIMARY KEY (user_id, role_id),

                            CONSTRAINT fk_user_roles_user
                                FOREIGN KEY (user_id)
                                    REFERENCES user_table(user_id),

                            CONSTRAINT fk_user_roles_role
                                FOREIGN KEY (role_id)
                                    REFERENCES role(id)
);